# ========================================================================
# SETTINGS MENU
# ========================================================================

- id: bsettingsmenu
  bg_color: paper_white
  widgets:
    - label:
        text: "Settings"
        align: TOP_MID
        y: 2
        text_font: font1

    - label:
        id: menu_temp_item
        text: "> Temperature"
        align: TOP_LEFT
        x: 10
        y: 18
        text_font: font1
    - label:
        id: menu_humidity_item
        text: "  Humidity"
        align: TOP_LEFT
        x: 10
        y: 30
        text_font: font1
    - label:
        id: menu_light_item
        text: "  Lighting"
        align: TOP_LEFT
        x: 10
        y: 42
        text_font: font1
    - label:
        id: menu_air_item
        text: "  Air Exchange"
        align: TOP_LEFT
        x: 10
        y: 54
        text_font: font1
    - label:
        id: menu_water_item
        text: "  Water Calibration"
        align: TOP_LEFT
        x: 10
        y: 66
        text_font: font1
    - label:
        id: menu_system_item
        text: "  System"
        align: TOP_LEFT
        x: 10
        y: 78
        text_font: font1

    - obj:
        x: 0
        y: 107
        width: 73
        height: 20
        radius: 0
        border_width: 0
        bg_color: paper_black
        widgets:
          - label:
              text: "Back"
              align: CENTER
              text_color: paper_white
              text_font: font1
    - obj:
        x: 75
        y: 107
        width: 73
        height: 20
        radius: 0
        border_width: 0
        bg_color: paper_black
        widgets:
          - label:
              text: "Up"
              align: CENTER
              text_color: paper_white
              text_font: font1
    - obj:
        x: 150
        y: 107
        width: 73
        height: 20
        radius: 0
        border_width: 0
        bg_color: paper_black
        widgets:
          - label:
              text: "Down"
              align: CENTER
              text_color: paper_white
              text_font: font1
    - obj:
        x: 225
        y: 107
        width: 71
        height: 20
        radius: 0
        border_width: 0
        bg_color: paper_black
        widgets:
          - label:
              text: "Select"
              align: CENTER
              text_color: paper_white
              text_font: font1
