# ========================================================================
# TEMPERATURE SETTINGS
# ========================================================================

- id: ctempsettings
  bg_color: paper_white
  widgets:
    - label:
        text: "Temperature"
        align: TOP_MID
        y: 2
        text_font: font1
    - label:
        id: temp_current_label
        text: "Current: --.-°C"
        align: TOP_LEFT
        x: 10
        y: 16
        text_font: font1

    - label:
        id: temp_enabled_carat
        text: ">"
        align: TOP_LEFT
        x: 5
        y: 29
        text_font: font1
    - label:
        text: "Control"
        align: TOP_LEFT
        x: 17
        y: 29
        text_font: font1
    - label:
        id: temp_enabled_value
        text: "OFF"
        align: TOP_RIGHT
        x: -10
        y: 29
        text_font: font1

    - label:
        id: temp_target_carat
        text: " "
        align: TOP_LEFT
        x: 5
        y: 42
        text_font: font1
    - label:
        text: "Target"
        align: TOP_LEFT
        x: 17
        y: 42
        text_font: font1
    - label:
        id: temp_target_value
        text: "--.-°C"
        align: TOP_RIGHT
        x: -10
        y: 42
        text_font: font1

    - label:
        id: temp_hysteresis_carat
        text: " "
        align: TOP_LEFT
        x: 5
        y: 55
        text_font: font1
    - label:
        text: "Hysteresis"
        align: TOP_LEFT
        x: 17
        y: 55
        text_font: font1
    - label:
        id: temp_hysteresis_value
        text: "--.--°C"
        align: TOP_RIGHT
        x: -10
        y: 55
        text_font: font1

    - label:
        id: temp_warn_min_carat
        text: " "
        align: TOP_LEFT
        x: 5
        y: 68
        text_font: font1
    - label:
        text: "Warning low"
        align: TOP_LEFT
        x: 17
        y: 68
        text_font: font1
    - label:
        id: temp_warn_min_value
        text: "--.-°C"
        align: TOP_RIGHT
        x: -10
        y: 68
        text_font: font1

    - label:
        id: temp_warn_max_carat
        text: " "
        align: TOP_LEFT
        x: 5
        y: 81
        text_font: font1
    - label:
        text: "Warning high"
        align: TOP_LEFT
        x: 17
        y: 81
        text_font: font1
    - label:
        id: temp_warn_max_value
        text: "--.-°C"
        align: TOP_RIGHT
        x: -10
        y: 81
        text_font: font1

    - obj:
        x: 0
        y: 107
        width: 73
        height: 20
        radius: 0
        border_width: 0
        bg_color: paper_black
        widgets:
          - label:
              text: "Back"
              align: CENTER
              text_color: paper_white
              text_font: font1
    - obj:
        x: 75
        y: 107
        width: 73
        height: 20
        radius: 0
        border_width: 0
        bg_color: paper_black
        widgets:
          - label:
              id: temp_minus_label
              text: "Off"
              align: CENTER
              text_color: paper_white
              text_font: font1
    - obj:
        x: 150
        y: 107
        width: 73
        height: 20
        radius: 0
        border_width: 0
        bg_color: paper_black
        widgets:
          - label:
              id: temp_plus_label
              text: "On"
              align: CENTER
              text_color: paper_white
              text_font: font1
    - obj:
        x: 225
        y: 107
        width: 71
        height: 20
        radius: 0
        border_width: 0
        bg_color: paper_black
        widgets:
          - label:
              text: "Next"
              align: CENTER
              text_color: paper_white
              text_font: font1
