# ========================================================================
# AIR EXCHANGE SETTINGS
# ========================================================================

- id: fairsettings
  bg_color: paper_white
  widgets:
    - label:
        text: "Air Exchange"
        align: TOP_MID
        y: 2
        text_font: font1
    - label:
        id: air_status_label
        text: "Fan: OFF (--- RPM)"
        align: TOP_LEFT
        x: 10
        y: 18
        text_font: font1

    - label:
        id: air_period_carat
        text: ">"
        align: TOP_LEFT
        x: 5
        y: 38
        text_font: font1
    - label:
        text: "Period"
        align: TOP_LEFT
        x: 17
        y: 38
        text_font: font1
    - label:
        id: air_period_value
        text: "--- min"
        align: TOP_RIGHT
        x: -10
        y: 38
        text_font: font1

    - label:
        id: air_duration_carat
        text: " "
        align: TOP_LEFT
        x: 5
        y: 55
        text_font: font1
    - label:
        text: "Run duration"
        align: TOP_LEFT
        x: 17
        y: 55
        text_font: font1
    - label:
        id: air_duration_value
        text: "--- sec"
        align: TOP_RIGHT
        x: -10
        y: 55
        text_font: font1

    - label:
        id: air_speed_carat
        text: " "
        align: TOP_LEFT
        x: 5
        y: 72
        text_font: font1
    - label:
        text: "Fan speed"
        align: TOP_LEFT
        x: 17
        y: 72
        text_font: font1
    - label:
        id: air_speed_value
        text: "---%"
        align: TOP_RIGHT
        x: -10
        y: 72
        text_font: font1

    - label:
        id: air_next_cycle_label
        text: "Next cycle: --"
        align: TOP_LEFT
        x: 10
        y: 89
        text_font: font1

    - obj:
        x: 0
        y: 107
        width: 73
        height: 20
        radius: 0
        border_width: 0
        bg_color: paper_black
        widgets:
          - label:
              text: "Back"
              align: CENTER
              text_color: paper_white
              text_font: font1
    - obj:
        x: 75
        y: 107
        width: 73
        height: 20
        radius: 0
        border_width: 0
        bg_color: paper_black
        widgets:
          - label:
              text: "-"
              align: CENTER
              text_color: paper_white
              text_font: font1
    - obj:
        x: 150
        y: 107
        width: 73
        height: 20
        radius: 0
        border_width: 0
        bg_color: paper_black
        widgets:
          - label:
              text: "+"
              align: CENTER
              text_color: paper_white
              text_font: font1
    - obj:
        x: 225
        y: 107
        width: 71
        height: 20
        radius: 0
        border_width: 0
        bg_color: paper_black
        widgets:
          - label:
              text: "Next"
              align: CENTER
              text_color: paper_white
              text_font: font1
