# ========================================================================
# SYSTEM SETTINGS AND INFORMATION
# ========================================================================

- id: hsystemsettings
  bg_color: paper_white
  widgets:
    - label:
        text: "System"
        align: TOP_MID
        y: 2
        text_font: font1

    - label:
        id: system_timezone_marker
        text: ">"
        align: TOP_LEFT
        x: 5
        y: 20
        text_font: font1
    - label:
        text: "Timezone"
        align: TOP_LEFT
        x: 17
        y: 20
        text_font: font1
    - label:
        id: system_timezone_value
        text: "--"
        align: TOP_RIGHT
        x: -10
        y: 20
        text_font: font1

    - label:
        id: system_orientation_marker
        text: " "
        align: TOP_LEFT
        x: 5
        y: 38
        text_font: font1
    - label:
        text: "Flip screen"
        align: TOP_LEFT
        x: 17
        y: 38
        text_font: font1
    - label:
        id: system_orientation_value
        text: "Off"
        align: TOP_RIGHT
        x: -10
        y: 38
        text_font: font1

    - label:
        text: "Voltage"
        align: TOP_LEFT
        x: 17
        y: 56
        text_font: font1
    - label:
        id: system_voltage_value
        text: "--.--V"
        align: TOP_RIGHT
        x: -10
        y: 56
        text_font: font1

    - label:
        text: "WiFi"
        align: TOP_LEFT
        x: 17
        y: 74
        text_font: font1
    - label:
        id: system_ssid_value
        text: "--"
        align: TOP_RIGHT
        x: -10
        y: 74
        text_font: font1

    - label:
        text: "IP"
        align: TOP_LEFT
        x: 17
        y: 90
        text_font: font1
    - label:
        id: system_ip_value
        text: "--"
        align: TOP_RIGHT
        x: -10
        y: 90
        text_font: font1

    - obj:
        x: 0
        y: 107
        width: 73
        height: 20
        radius: 0
        border_width: 0
        bg_color: paper_black
        widgets:
          - label:
              text: "Back"
              align: CENTER
              text_color: paper_white
              text_font: font1
    - obj:
        x: 75
        y: 107
        width: 73
        height: 20
        radius: 0
        border_width: 0
        bg_color: paper_black
        widgets:
          - label:
              text: "-"
              align: CENTER
              text_color: paper_white
              text_font: font1
    - obj:
        x: 150
        y: 107
        width: 73
        height: 20
        radius: 0
        border_width: 0
        bg_color: paper_black
        widgets:
          - label:
              text: "+"
              align: CENTER
              text_color: paper_white
              text_font: font1
    - obj:
        x: 225
        y: 107
        width: 71
        height: 20
        radius: 0
        border_width: 0
        bg_color: paper_black
        widgets:
          - label:
              text: "Next"
              align: CENTER
              text_color: paper_white
              text_font: font1
