# ========================================================================
# LIGHT SETTINGS
# ========================================================================

- id: elightsettings
  bg_color: paper_white
  widgets:
    - label:
        text: "Lighting"
        align: TOP_MID
        y: 2
        text_font: font1

    - label:
        id: light_sunrise_carat
        text: ">"
        align: TOP_LEFT
        x: 5
        y: 18
        text_font: font1
    - label:
        text: "Sunrise"
        align: TOP_LEFT
        x: 17
        y: 18
        text_font: font1
    - label:
        id: light_sunrise_value
        text: "--:00"
        align: TOP_RIGHT
        x: -10
        y: 18
        text_font: font1

    - label:
        id: light_duration_carat
        text: " "
        align: TOP_LEFT
        x: 5
        y: 31
        text_font: font1
    - label:
        text: "Duration"
        align: TOP_LEFT
        x: 17
        y: 31
        text_font: font1
    - label:
        id: light_duration_value
        text: "--.-- hrs"
        align: TOP_RIGHT
        x: -10
        y: 31
        text_font: font1

    - label:
        id: light_white_carat
        text: " "
        align: TOP_LEFT
        x: 5
        y: 44
        text_font: font1
    - label:
        text: "White"
        align: TOP_LEFT
        x: 17
        y: 44
        text_font: font1
    - label:
        id: light_white_value
        text: "---- lux"
        align: TOP_RIGHT
        x: -10
        y: 44
        text_font: font1

    - label:
        id: light_red_carat
        text: " "
        align: TOP_LEFT
        x: 5
        y: 57
        text_font: font1
    - label:
        text: "Red"
        align: TOP_LEFT
        x: 17
        y: 57
        text_font: font1
    - label:
        id: light_red_value
        text: "---%"
        align: TOP_RIGHT
        x: -10
        y: 57
        text_font: font1

    - label:
        id: light_green_carat
        text: " "
        align: TOP_LEFT
        x: 5
        y: 70
        text_font: font1
    - label:
        text: "Green"
        align: TOP_LEFT
        x: 17
        y: 70
        text_font: font1
    - label:
        id: light_green_value
        text: "---%"
        align: TOP_RIGHT
        x: -10
        y: 70
        text_font: font1

    - label:
        id: light_blue_carat
        text: " "
        align: TOP_LEFT
        x: 5
        y: 83
        text_font: font1
    - label:
        text: "Blue"
        align: TOP_LEFT
        x: 17
        y: 83
        text_font: font1
    - label:
        id: light_blue_value
        text: "---%"
        align: TOP_RIGHT
        x: -10
        y: 83
        text_font: font1

    - obj:
        x: 0
        y: 107
        width: 73
        height: 20
        radius: 0
        border_width: 0
        bg_color: paper_black
        widgets:
          - label:
              text: "Back"
              align: CENTER
              text_color: paper_white
              text_font: font1
    - obj:
        x: 75
        y: 107
        width: 73
        height: 20
        radius: 0
        border_width: 0
        bg_color: paper_black
        widgets:
          - label:
              text: "-"
              align: CENTER
              text_color: paper_white
              text_font: font1
    - obj:
        x: 150
        y: 107
        width: 73
        height: 20
        radius: 0
        border_width: 0
        bg_color: paper_black
        widgets:
          - label:
              text: "+"
              align: CENTER
              text_color: paper_white
              text_font: font1
    - obj:
        x: 225
        y: 107
        width: 71
        height: 20
        radius: 0
        border_width: 0
        bg_color: paper_black
        widgets:
          - label:
              text: "Next"
              align: CENTER
              text_color: paper_white
              text_font: font1
